### ISSUE TITLE
Instruction for starting on customer port are incorrect

### ISSUE THREAD

**Issue by chris-hailstorm** [PGBI/kong-dashboard#55] opened 2016-09-14 19:08 UTC
The instructions say:
# To start Kong Dashboard on a custom port

npm start -- -p [port]

However using that command results in this error:

Error: ENOENT, open '/usr/local/kong-dashboard/node_modules/-p/package.json'

Appears to be treating the "-p" as a module to load.

**Comment by PGBI** [comment] 2017-12-20 08:46
Closing as I can't reproduce with Kong-dashboard v3 and node6/npm3 ; node7/npm4 ; node8/npm5. 

This was either fixed in the last version of Kong-Dashboard or it may be caused by an older version of npm we do no support that doesn't accept the "npm run cmd -- args" syntax.

**Closed by PGBI** 2017-12-20 08:46 UTC
