### ISSUE TITLE
Cannot GET /go/home

### ISSUE THREAD

**Issue by gtrias** [PGBI/kong-dashboard#15] opened 2015-12-23 16:06 UTC
Tried with manual install and docker one. With kong running on its docker.

Everything went OK on the install or docker deploy, the server is running apparently fine.
But when you try to browse http://localhost:8080 I've get this message ``Cannot GET /go/home``.

Any idea how to solve?

**Comment by PGBI** [comment] 2015-12-23 19:36
What's your environment? Once the docker container is started, you should browse http://localhost:8080 if you are on linux, otherwise, it should be http://<IP of the VM hosting your docker server>:8080

Hopefully that will help. I'm still pretty new at docker.

**Comment by gtrias** [comment] 2015-12-23 21:29
I'm using arch linux but I don't think it's a docker issue because it happens the same installing kong-dashboard with installation from sources. The npm install doesn't work for me it gives to me an error with the dependencies.

**Comment by gtrias** [comment] 2015-12-23 21:30
Tomorrow I will try again maybe I can see what is the cause.

**Comment by PGBI** [comment] 2015-12-24 09:59
I've been unable to reproduce the problem (with docker and with npm). Can you please paste here what the output of your `npm install` command is?

**Comment by gtrias** [comment] 2015-12-24 11:03
Following the steps described here https://github.com/PGBI/kong-dashboard#npm-installation

``npm install -g kong-dashboard``

I get:

```bash
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
/usr/bin/kong-dashboard -> /usr/lib/node_modules/kong-dashboard/bin/kong-dashboard.js

> node-sass@3.4.2 install /usr/lib/node_modules/kong-dashboard/node_modules/node-sass
> node scripts/install.js




Binary downloaded and installed at /usr/lib/node_modules/kong-dashboard/node_modules/node-sass/vendor/linux-x64-47/binding.node

> kong-dashboard@1.0.1 install /usr/lib/node_modules/kong-dashboard
> node ./bin/kong-dashboard build

Downloading javascript librairies...
/usr/lib/node_modules/kong-dashboard/lib/kong-dashboard.js:21
            if (err) throw err;
                     ^

Error: Command failed: /bin/sh -c /usr/lib/node_modules/kong-dashboard/lib/../node_modules/.bin/bower install
/usr/lib/node_modules/kong-dashboard/node_modules/bower/node_modules/configstore/index.js:56
				throw err;
				^

Error: EACCES: permission denied, open '/root/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:584:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:431:33)
    at Object.create.all.get (/usr/lib/node_modules/kong-dashboard/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/kong-dashboard/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/lib/node_modules/kong-dashboard/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/lib/node_modules/kong-dashboard/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/lib/node_modules/kong-dashboard/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "kong-dashboard"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! kong-dashboard@1.0.1 install: `node ./bin/kong-dashboard build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kong-dashboard@1.0.1 install script 'node ./bin/kong-dashboard build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kong-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/kong-dashboard build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kong-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kong-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/genar/src/npm-debug.log
```
The folder ``/root/.config/configstore/`` doesn't exists, maybe this is the problem.

In the other hand, I'm seeing that ``/root/.npm`` have wrong user:group (always have permissions issues with npm) but I running the command with sudo so, this shouldn't affect.

**Comment by gtrias** [comment] 2015-12-24 11:04
My npm version:
```
[genar@fry src]$ npm -v
3.5.2
```
My nodejs version:
```
[genar@fry src]$ node -v
v5.3.0
```

**Comment by gtrias** [comment] 2015-12-24 11:06
Changing user:group for ``/root/.npm`` to root:root has no effect, I've got the same error.

**Comment by PGBI** [comment] 2015-12-24 18:01
There is definitely something wrong with node and npm during the install process.

If you checkout d501a95f68dc, i've added a vagrantFile if you want to install Kong Dashboard with vagrant until I figure out what's wrong with your setup.

**Comment by PGBI** [comment] 2015-12-26 18:50
Just tested on a VM running arch linux, node (5.3.0) and npm (3.5.2) and I couldn't reproduce the error.

Are you trying to install kong-dashboard as root? Cause you should not. If you have difficulties installing an npm package globally without having root permissions, you can follow npm instructions here: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by gtrias** [comment] 2015-12-29 18:19
Yeah, maybe is npm permissions mesh. But anyway since docker container is an isolated environment it should work as expected. And when I installed from sources I got the same original error "cannot get /go/home"... I don't have vagrant installed on this computer so, I will try to use vagrant install when I can.

**Comment by PGBI** [comment] 2016-01-25 18:37
I tried again on a fresh arch linux installation. Closing this ticket as I do not face any error, whether it's with npm or docker.

**Closed by PGBI** 2016-01-25 18:37 UTC

**Comment by mitchellfranklin** [comment] 2016-03-04 12:26
generally the error relates to legacy NodeJS requirements if you run sudo apt-get install nodejs-legacy this should fix the issue
