### ISSUE TITLE
Getting "Cannot GET /" when visiting localhost:8080

### ISSUE THREAD

**Issue by mitchellfranklin** [PGBI/kong-dashboard#30] opened 2016-03-09 05:33 UTC
Hi All,

I have successfully installed Kong-Dashboard however when I go to http://localhost:8080 the screen returned is Cannot GET /. 

any assistance would be greatly appreciated.

Thanks

Mitch

**Comment by gajen0981** [comment] 2016-03-11 19:48
I am getting the same error on RHEL 7 environment.

**Comment by gajen0981** [comment] 2016-03-15 19:02
Found the issue and it's not with the code and it's because of directory permissions and didn't properly install the bower requirements. 

This worked:
```
git clone https://github.com/PGBI/kong-dashboard.git
cd kong-dashboard
bower update
npm install
npm start

```

**Comment by haikuo81** [comment] 2016-04-17 07:31
I am also get "Cannot GET /", @gajen0981, could you please tell me which directory should give correct permissions?

**Comment by nimboya** [comment] 2016-07-21 04:10
Thank you @gajen0981 What you said worked had to update the bower and do npm install to compile the assets. But still could not access the APIs already created previously.

Also if you use Ubuntu ensure you install the node-legacy for it to some npm commands. And ensure you allow all permission on the folder so as to allow creation of files and folders easily

So in my case i had to do this:

```
git clone https://github.com/PGBI/kong-dashboard.git
sudo chmod -R 777 kong-dashboard
cd kong-dashboard
npm install
bower update
npm install
npm start
```

**Comment by PGBI** [comment] 2017-12-15 10:51
This was caused by an error at build time. Closing as npm package for Kong-Dashboard is now shipped pre-built.

**Closed by PGBI** 2017-12-15 10:51 UTC
