### ISSUE TITLE
Key-Auth default "key_names" field incorrect

### ISSUE THREAD

**Issue by CraigChilds94** [PGBI/kong-dashboard#72] opened 2017-01-19 12:35 UTC
If you set the `key-auth` plugin on an API and don't provide the "key names" field it is populated with "function" whereas it should be "apikey".

This is the version of the image I am using (as outputted with `docker images`):

`pgbi/kong-dashboard                       latest              0318a50f4503        3 months ago        147 MB`

**Comment by CraigChilds94** [comment] 2017-05-26 15:50
@PGBI Are you still maintaining this project?

**Comment by PGBI** [comment] 2017-05-26 16:18
Yep. Feel free to submit a PR, I'll be more than happy to take a look :)

**Comment by PGBI** [comment] 2017-12-19 10:06
This was caused by Kong 0.9 (and before?) which would return:

```
{
  "id":"59b85891-e229-411f-9dd7-86981cc59692",
  "created_at":1513677794000,
  "enabled":true,
  "name":"key-auth",
  "config":{
    "hide_credentials":false,
    "key_names":["function"]
  }
}
```
to such an http request:
```
POST /plugins
{"name":"key-auth","config":{"hide_credentials":false}}
```

Closing as I can't reproduce with Kong-Dashboard 3.0 & Kong 0.11. I guess it was fixed on their side.

**Closed by PGBI** 2017-12-19 10:06 UTC
